apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: vitadairy-reward-be-test
build:
  local:
    push: false
  artifacts:
    - image: vtan/multi-client
      context: client
      docker:
        dockerfile: Dockerfile
    - image: vtan/multi-server
      context: server
      docker:
        dockerfile: Dockerfile
    - image: vtan/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - k8s/*
